### PR TITLE
Move API interaction to client

### PR DESCRIPTION
**Pull request by lasseborly**
We are removing the last remnants of the API paths and migrating the functionality into the client side of the application.

### CODE REVIEW

**Comment by lasseborly** [comment]
Hooking everything up it seems that the [API](https://github.com/BoostV/process-optimizer-api) is "missing" CORS setup before the client is able to communicate with the API.

I'll continue work on the API repo and ready a PR that incorporates a configurable way of getting CORS functionality.

Until then, this does not move forward and I am closing down https://github.com/BoostV/process-optimizer-frontend/pull/134 that duplicates some of the work we are doing here.

**Comment by lasseborly** [comment]
We have https://github.com/BoostV/process-optimizer-api/pull/41 merged and this is ready for review.

**Review by langdal — APPROVED** [review]
Looks good. I have reverted a few parts of the devcontainer configuration and added a method for customizing the API_URL when running the frontend using docker

**Comment by lasseborly** [comment]
> Looks good. I have reverted a few parts of the devcontainer configuration and added a method for customizing the API_URL when running the frontend using docker

Very nice @langdal 🎉

**Pull request merged**
