### PR TITLE
Help text for plots and width of plots

### PR DESCRIPTION
**Pull request by AkselObdrup**
Addition of help text for convergence plot and objective plot (@SQBL please review if the text is fitting). This is related to issue #9.

Furthermore the width of both plots have been set to 800 pixels to avoid cropping by the card. This is related to issue #70 (@j-or Please review if this is a suitable fix).

### CODE REVIEW

**Comment by j-or** [comment]
Looks good! I have changed the texts to use the Typography component, so we use the same sizes and styles everywhere. While I was at it, I removed the bullet points next to the plots (not something you did, I just forgot to remove them earlier 😄 ) Hope that's ok, let me know if something looks off. 

For the image width I'm thinking that setting maxWidth instead of width might be good? That way, the image will be its actual size until it no longer fits the card and then scale to the width of the card. You can try it by adding a className to the two `` and then adding the maxWidth: '100%' style in the plots.style.tsx file (exactly as I've done with the two `<li>`). Let me know if that doesn't make sense

**Comment by AkselObdrup** [comment]
Thanks, I agree that the formatting looks more consistent with the typography component (and nice that you removed the bullet points).
I also think your idea about setting maxWidth is more elegant. Please check if the latest commit corresponds to your idea (it seems to behave nicely).

**Comment by j-or** [comment]
Awesome, that's exactly what I was thinking. Hmm, it seems we now have a very large convergence plot though, because the backend spits out a big image? At least in my example. Unless we want a huge plot, maybe we should separately set the convergence img width=100% and maxWidth=some value (maybe the 800 you used earlier) so it's not quite as massive? 
large_plot

**Review by j-or — APPROVED** [review]

**Comment by j-or** [comment]
I made a small adjustment so the objective plot gets more space in case of many inputs. We can of course always adjust later. Nice work, I've approved so go ahead and merge if you want.

**Pull request merged**
